Solution/Cinepolis/CinePolis.Web.Touch/Models/Payment/PinViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using CinePolis.Web.Touch.App_Data;

namespace CinePolis.Web.Touch.Models.Payment
{
    public class PinViewModel
    {
        public string MoviePoster { get; set; }
        public string MovieTitle { get; set; }
        public DateTimeOffset ScheduledTime { get; set; }
        public List<TicketSelection> Tickets { get; set; }
        public int TicketCount { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "validationError_PinRequired")]
        [RegularExpression("^(\\d{4})$", ErrorMessageResourceType = typeof(Resources), ErrorMessageResourceName = "validationError_PinInvalid")]
        public string PinCode { get; set; }
    }
}

Solution/Cinepolis/CinePolis.Web.Touch/Controllers/PaymentController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using CinePolis.Domain.Entities;
using CinePolis.Domain.Services;
using CinePolis.Web.Touch.App_Data;
using CinePolis.Web.Touch.Models;
using CinePolis.Web.Touch.Models.Payment;

namespace CinePolis.Web.Touch.Controllers
{
    public class PaymentController : Controller
    {
        private readonly IPriceService _priceService;

        public PaymentController(IPriceService priceService)
        {
            _priceService = priceService;
        }

        [HttpGet]
        public ActionResult Pin()
        {
            OrderData orderData = Session["Order"] as OrderData;
            if (orderData == null)
                return RedirectToActionPermanent("Index", "Home");

            List<Price> prices = _priceService.GetAvailablePrices();

            PinViewModel model = new PinViewModel
            {
                MoviePoster = orderData.MoviePoster,
                MovieTitle = orderData.MovieTitle,
                ScheduledTime = orderData.ScheduledTime,
                TicketCount = orderData.TicketCount,
                Tickets = orderData.Tickets
                    .Select(kvp =>
                    {
                        Price price = prices.First(p => p.Id == kvp.Key);

                        return new TicketSelection
                        {
                            PriceId = kvp.Key,
                            SelectedAmount = kvp.Value,
                            DefaultPrice = price.Value,
                            FinalPrice = price.CalculateFinalPrice(),
                            DiscountDescription = price.Discount.Description
                        };
                    })
                    .ToList()
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Pin(PinViewModel model)
        {
            OrderData orderData = Session["Order"] as OrderData;
            if (orderData == null)
                return RedirectToActionPermanent("Index", "Home");

            if (ModelState.IsValid)
            {
                if (model.PinCode.Any(c => c != '0'))
                    return RedirectToActionPermanent("Confirm", "Order");
                ModelState.AddModelError("PinCode", Resources.validationError_PinInvalid);
            }

            List<Price> prices = _priceService.GetAvailablePrices();

            model.MoviePoster = orderData.MoviePoster;
            model.MovieTitle = orderData.MovieTitle;
            model.ScheduledTime = orderData.ScheduledTime;
            model.TicketCount = orderData.TicketCount;
            model.Tickets = orderData.Tickets
                .Select(kvp =>
                {
                    Price price = prices.First(p => p.Id == kvp.Key);

                    return new TicketSelection
                    {
                        PriceId = kvp.Key,
                        SelectedAmount = kvp.Value,
                        DefaultPrice = price.Value,
                        FinalPrice = price.CalculateFinalPrice(),
                        DiscountDescription = price.Discount.Description
                    };
                })
                .ToList();

            return View(model);
        }
    }
}

Solution/Cinepolis/CinePolis.Web.Touch/Views/Payment/Pin.cshtml
@model CinePolis.Web.Touch.Models.Payment.PinViewModel
@{
    ViewBag.Title = "Pin";
}

@using (Html.BeginForm("Pin", "Payment", FormMethod.Post, new { id = "main-form" }))
{
    @Html.ValidationSummary()
    
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-9">
            <p class="ultra-bold">
                <span class="label label-primary">6.</span>
                Voer uw pincode in
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title" id="panel-title">Uw selectie<a href="#panel-title" class="anchorjs-link"><span class="anchorjs-icon"></span></a></h3>
                </div>
                <div class="panel-body">
                    <img src="@Model.MoviePoster" width="231" height="300" />
                    <hr />
                    <table>
                        <tr>
                            <td class="col-lg-3">Film:</td>
                            <td>@Model.MovieTitle</td>
                        </tr>
                        <tr>
                            <td class="col-lg-3">Dag:</td>
                            <td>

                                @if (Model.ScheduledTime.Date == DateTime.Now.Date)
                                {
                                    @:Vandaag
                        }
                                else if (Model.ScheduledTime.Date == DateTime.Now.AddDays(1).Date)
                                {
                                    @:Morgen
                        }
                                else
                                {
                                    @Model.ScheduledTime.ToString("dddd")
                                }

                            </td>
                        </tr>
                        <tr>
                            <td class="col-lg-3">Tijd:</td>
                            <td>@Model.ScheduledTime.ToString("t")</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-sm-9">
            @Html.PasswordFor(m => m.PinCode, new { maxlength = 4 })
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <a class="btn btn-lg btn-primary pull-left" href="@Url.Action("SelectPayment", "Order")"><span aria-hidden="true" class="glyphicon glyphicon-chevron-left"></span> Andere vorm van betaling</a>
        </div>
        <div class="col-lg-6">
            <a class="btn btn-lg btn-primary pull-right" onclick="document.getElementById('main-form').submit();">Betalen <span aria-hidden="true" class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
}